---
title: "Analyze data"
date: "`r format(Sys.time(), '%B %d, %Y. %H:%M')`"
editor_options:
  chunk_output_type: console
output:
  html_document: 
    df_print: tibble
    highlight: kate
    number_sections: yes
    theme: paper
    toc: yes
---

```{r, echo = FALSE}
# Collapse code and output into one box for readability
knitr::opts_chunk$set(
    collapse = TRUE,
    comment = "#>"
)
```

**Purpose**: 

```{r message=FALSE}
# Load packages
library(tidyverse)
library(here)
library(patchwork)
library(maps)
library(paletteer)
```

```{r warning=FALSE}
# Set plotting theme
theme_set(
  theme_void() +
    theme(
      legend.position = c(0.92, 0.3),
      text = element_text(family = "Roboto", color = "#444440"),
      plot.background = element_rect(fill = "#f5f5f5", color = NA),
      plot.title = element_text(hjust = 0.1),
      plot.subtitle = element_text(hjust = 0.2, margin = margin(t = 10, b = -15))
      )
  )
```

# Load
```{r message=FALSE}
# Load
load(here("data", "cdc_clean.RData"))

# Extract US map
us_states <- map_data("state")
```

# Analyze
```{r}
# Plot health insurance coverage
custom_breaks <- seq(0, 40, 10)
p_access <- df %>% 
  filter(parameter == "access2") %>% 
  ggplot() +
  geom_polygon(data = us_states,
               aes(x = long, y = lat, group = group),
               fill = "lightgrey", color = "gray", alpha = 0.2) +
  geom_point(aes(x = long, y = lat, 
                 size = prevalence_adj, color = prevalence_adj, alpha = prevalence_adj),
             shape = 20, stroke = FALSE) +
  labs(title = "Model-based estimates for:", 
       subtitle = "A: current lack of health insurance among adults aged 18–64 years – 2016") +
  scale_size_continuous(name = "Prevalence (%)", range = c(1,8), breaks = custom_breaks) +
  scale_alpha_continuous(name = "Prevalence (%)", breaks = custom_breaks) +
  scale_colour_paletteer_c(name = "Prevalence (%)", package = "scico", palette = "berlin") +
  guides(color = guide_legend()) +
  coord_map()

# Plot high blood pressure
custom_breaks <- seq(0, 50, 5)
p_bp <- df %>% 
  filter(parameter == "bphigh") %>% 
  ggplot() +
  geom_polygon(data = us_states,
               aes(x = long, y = lat, group = group),
               fill = "lightgrey", color = "gray", alpha = 0.2) +
  geom_point(aes(x = long, y = lat, 
                 size = prevalence_adj, color = prevalence_adj, alpha = prevalence_adj),
             shape = 20, stroke = FALSE) +
  labs(title = "",
       subtitle= "B: high blood pressure among adults aged ≥ 18 years – 2015") +
  scale_size_continuous(name = "Prevalence (%)", range = c(1,8), breaks = custom_breaks) +
  scale_alpha_continuous(name = "Prevalence (%)", breaks = custom_breaks) +
  scale_colour_paletteer_c(name = "Prevalence (%)", package = "scico", palette = "berlin") +
  guides(color = guide_legend()) +
  coord_map()

# Combine
p <- p_access / p_bp
```

```{r}
p_access_tx <- df %>% 
  filter(parameter == "access2", state == "TX") %>% 
  mutate(city = fct_reorder(city, prevalence_adj),
         group = prevalence_adj > 40) %>% 
  ggplot(aes(city, prevalence_adj, color = group)) +
  geom_point(size = 3) +
  labs(title = "A Closer Look: Texas",
       subtitle = "Lack of health insurance by city – 2016",
       x = "",
       y = "Age-adjusted Prevalence") +
  guides(color = FALSE) +
  scale_color_manual(values = c("TRUE" = "#10233d", 
                                "FALSE" = "#e3e8ef")) +
  coord_flip(ylim = c(0, 50)) +
  theme_bw()
```

# Save
```{r}
ggsave(plot = p,
       filename = "maps.png",
       path = here("figures"),
       height = 8, width = 8,
       dpi = 300)

ggsave(plot = p_access_tx,
       filename = "access_tx.png",
       path = here("figures"),
       height = 8, width = 4,
       dpi = 300)
```

